include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
