include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_return: error
    dead_code: info
    unused_import: error
    unused_local_variable: warning
    unnecessary_cast: warning
    unnecessary_null_comparison: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"
    - "build/**"
    - ".dart_tool/**"
    - "coverage/**"

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - avoid_returning_null
    - avoid_unnecessary_containers
    - avoid_void_async
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sort_child_properties_last
    - unawaited_futures
    - use_key_in_widget_constructors
    - require_trailing_commas
